/* eslint-disable */
import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "\n  mutation activateAdmin($activateAdminId: ID!) {\n    activateAdmin(id: $activateAdminId) {\n      avatarFilename\n      createdAt\n      email\n      fullName\n      id\n      organizationName\n      permissionType\n      phoneNumber\n      roleName\n      status\n      updatedAt\n      userType\n    }\n  }\n": typeof types.ActivateAdminDocument,
    "\n    query admin($adminId: ID!) {\n      admin(id: $adminId) {\n        createdAt\n        email\n        fullName\n        id\n        organizationName\n        permissionType\n        roleName\n        status\n        updatedAt\n        userType\n        phoneNumber\n      }\n    }\n  ": typeof types.AdminDocument,
    "\n  query admins($paginationInput: AdminPaginationInput) {\n    admins(paginationInput: $paginationInput) {\n      meta {\n        hasNext\n        hasPrevious\n        limit\n        page\n        total\n        totalPages\n      }\n      items {\n        createdAt\n        email\n        fullName\n        id\n        organizationName\n        permissionType\n        roleName\n        status\n        updatedAt\n        userType\n        phoneNumber\n      }\n    }\n  }\n": typeof types.AdminsDocument,
    "\n  mutation createAdmin($createAdminInput: CreateAdminInput!) {\n    createAdmin(createAdminInput: $createAdminInput) {\n      createdAt\n      email\n      fullName\n      id\n      organizationName\n      permissionType\n      roleName\n      status\n      updatedAt\n      userType\n      phoneNumber\n    }\n  }\n": typeof types.CreateAdminDocument,
    "\n  mutation deactivateAdmin(\n    $deactivateAdminId: ID!\n    $input: DeactivateAdminInput!\n  ) {\n    deactivateAdmin(id: $deactivateAdminId, input: $input) {\n      avatarFilename\n      createdAt\n      email\n      fullName\n      id\n      organizationName\n      permissionType\n      phoneNumber\n      roleName\n      status\n      updatedAt\n      userType\n    }\n  }\n": typeof types.DeactivateAdminDocument,
    "\n  query meAdmin {\n    meAdmin {\n      id\n      createdAt\n      email\n      fullName\n      organizationName\n      permissionType\n      roleName\n      status\n      updatedAt\n      userType\n      phoneNumber\n      avatarFilename\n    }\n  }\n": typeof types.MeAdminDocument,
    "\n  mutation removeAdmin($removeAdminId: ID!) {\n    removeAdmin(id: $removeAdminId)\n  }\n": typeof types.RemoveAdminDocument,
    "\n  mutation updateAdmin(\n    $updateAdminId: ID!\n    $updateAdminInput: UpdateAdminInput!\n  ) {\n    updateAdmin(id: $updateAdminId, updateAdminInput: $updateAdminInput) {\n      createdAt\n      email\n      fullName\n      id\n      organizationName\n      permissionType\n      roleName\n      status\n      updatedAt\n      userType\n      phoneNumber\n    }\n  }\n": typeof types.UpdateAdminDocument,
    "\n  mutation adminChangePassword($input: AdminChangePasswordInput!) {\n    adminChangePassword(input: $input)\n  }\n": typeof types.AdminChangePasswordDocument,
    "\n  mutation adminForgotPassword($input: AdminForgotPasswordInput!) {\n    adminForgotPassword(input: $input)\n  }\n": typeof types.AdminForgotPasswordDocument,
    "\n  mutation adminLogin($input: AdminLoginInput!) {\n    adminLogin(input: $input) {\n      accessToken\n    }\n  }\n": typeof types.AdminLoginDocument,
    "\n  mutation adminResetPassword($input: AdminResetPasswordInput!) {\n    adminResetPassword(input: $input)\n  }\n": typeof types.AdminResetPasswordDocument,
    "\n  mutation adminVerifyPasswordResetOtp(\n    $input: VerifyAdminPasswordResetOtpInput!\n  ) {\n    adminVerifyPasswordResetOtp(input: $input) {\n      resetToken\n    }\n  }\n": typeof types.AdminVerifyPasswordResetOtpDocument,
    "\n  query categories($input: CategoryPaginationInput) {\n    categories(input: $input) {\n      meta {\n        hasNext\n        hasPrevious\n        limit\n        page\n        total\n        totalPages\n      }\n      items {\n        createdAt\n        descriptionAr\n        descriptionEn\n        id\n        nameAr\n        nameEn\n        parentId\n        updatedAt\n        parent {\n          createdAt\n          descriptionAr\n          descriptionEn\n          id\n          nameAr\n          nameEn\n          parentId\n          updatedAt\n        }\n      }\n    }\n  }\n": typeof types.CategoriesDocument,
    "\n  query category($categoryId: String!) {\n    category(id: $categoryId) {\n      createdAt\n      descriptionAr\n      descriptionEn\n      id\n      nameAr\n      nameEn\n      parent {\n        createdAt\n        descriptionAr\n        descriptionEn\n        id\n        nameAr\n        nameEn\n        parentId\n        updatedAt\n      }\n      parentId\n      updatedAt\n    }\n  }\n": typeof types.CategoryDocument,
    "\n  mutation createCategory($input: CreateCategoryInput!) {\n    createCategory(input: $input) {\n      createdAt\n      descriptionAr\n      descriptionEn\n      id\n      nameAr\n      nameEn\n      parentId\n      updatedAt\n    }\n  }\n": typeof types.CreateCategoryDocument,
    "\n  mutation removeCategory($removeCategoryId: String!) {\n    removeCategory(id: $removeCategoryId) {\n      id\n      createdAt\n      descriptionAr\n      descriptionEn\n      nameAr\n      nameEn\n      parentId\n      updatedAt\n    }\n  }\n": typeof types.RemoveCategoryDocument,
    "\n  mutation updateCategory($input: UpdateCategoryInput!) {\n    updateCategory(input: $input) {\n      createdAt\n      descriptionAr\n      descriptionEn\n      id\n      nameAr\n      nameEn\n      parentId\n      updatedAt\n    }\n  }\n": typeof types.UpdateCategoryDocument,
    "\n  query cities($pagination: CityPaginationInput) {\n    cities(pagination: $pagination) {\n      meta {\n        hasNext\n        hasPrevious\n        limit\n        page\n        total\n        totalPages\n      }\n      items {\n        countryId\n        createdAt\n        id\n        nameAr\n        nameEn\n        updatedAt\n        country {\n          code\n          createdAt\n          dialCode\n          id\n          nameAr\n          nameEn\n          updatedAt\n        }\n      }\n    }\n  }\n": typeof types.CitiesDocument,
    "\n  query city($cityId: ID!) {\n    city(id: $cityId) {\n      id\n      nameAr\n      nameEn\n      updatedAt\n      createdAt\n      countryId\n      country {\n        code\n        createdAt\n        dialCode\n        id\n        nameAr\n        nameEn\n        updatedAt\n      }\n    }\n  }\n": typeof types.CityDocument,
    "\n  query countries($pagination: CountryPaginationInput) {\n    countries(pagination: $pagination) {\n      meta {\n        hasNext\n        hasPrevious\n        limit\n        page\n        total\n        totalPages\n      }\n      items {\n        code\n        createdAt\n        dialCode\n        id\n        nameAr\n        nameEn\n        updatedAt\n      }\n    }\n  }\n": typeof types.CountriesDocument,
    "\n  mutation createCity($input: CreateCityInput!) {\n    createCity(input: $input) {\n      id\n      countryId\n      createdAt\n      nameAr\n      nameEn\n      updatedAt\n      country {\n        code\n        createdAt\n        dialCode\n        id\n        nameAr\n        nameEn\n        updatedAt\n      }\n    }\n  }\n": typeof types.CreateCityDocument,
    "\n  mutation removeCity($removeCityId: ID!) {\n    removeCity(id: $removeCityId) {\n      countryId\n      createdAt\n      id\n      nameAr\n      nameEn\n      updatedAt\n      country {\n        code\n        createdAt\n        dialCode\n        id\n        nameAr\n        nameEn\n        updatedAt\n      }\n    }\n  }\n": typeof types.RemoveCityDocument,
    "\n  mutation updateCity($input: UpdateCityInput!) {\n    updateCity(input: $input) {\n      countryId\n      createdAt\n      id\n      nameAr\n      nameEn\n      updatedAt\n      country {\n        code\n        createdAt\n        dialCode\n        id\n        nameAr\n        nameEn\n        updatedAt\n      }\n    }\n  }\n": typeof types.UpdateCityDocument,
    "\n  query adminPermissions($adminId: ID!) {\n    adminPermissions(adminId: $adminId) {\n      adminId\n      createdAt\n      id\n      permission {\n        action\n        createdAt\n        description\n        id\n        module\n        name\n        nameAr\n        permissionPlatform\n        resource\n        updatedAt\n      }\n      permissionId\n      updatedAt\n      admin {\n        createdAt\n        email\n        fullName\n        id\n        organizationName\n        permissionType\n        phoneNumber\n        roleName\n        status\n        updatedAt\n        userType\n      }\n    }\n  }\n": typeof types.AdminPermissionsDocument,
    "\n  mutation bulkAssignPermissionsToAdmin($input: BulkAssignPermissionsInput!) {\n    bulkAssignPermissionsToAdmin(input: $input) {\n      adminId\n      createdAt\n      id\n      permission {\n        resource\n        action\n        createdAt\n        description\n        id\n        module\n        name\n        nameAr\n        permissionPlatform\n        updatedAt\n      }\n      admin {\n        createdAt\n        email\n        fullName\n        id\n        organizationName\n        permissionType\n        phoneNumber\n        roleName\n        status\n        updatedAt\n        userType\n      }\n      permissionId\n      updatedAt\n    }\n  }\n": typeof types.BulkAssignPermissionsToAdminDocument,
    "\n  query permissions {\n    permissions {\n      action\n      createdAt\n      description\n      id\n      module\n      name\n      nameAr\n      permissionPlatform\n      resource\n      updatedAt\n    }\n  }\n": typeof types.PermissionsDocument,
    "\n  query getSetting {\n    getSetting {\n      aboutAr\n      aboutEn\n      email\n      phones\n      privacyPolicyAr\n      privacyPolicyEn\n      socialMediaLinks {\n        link\n        name\n      }\n      termsAr\n      termsEn\n      whatsappNumber\n    }\n  }\n": typeof types.GetSettingDocument,
    "\n  mutation setSetting($input: SettingInput!) {\n    setSetting(input: $input) {\n      aboutAr\n      aboutEn\n      email\n      phones\n      privacyPolicyAr\n      privacyPolicyEn\n      socialMediaLinks {\n        link\n        name\n      }\n      termsAr\n      termsEn\n      whatsappNumber\n    }\n  }\n": typeof types.SetSettingDocument,
    "\n  mutation activateUser($activateUserId: ID!) {\n    activateUser(id: $activateUserId) {\n      address\n      avatarFilename\n      bankName\n      categories {\n        createdAt\n        descriptionAr\n        descriptionEn\n        id\n        nameAr\n        nameEn\n        parentId\n        updatedAt\n      }\n      cityId\n      commercialRegistrationNumber\n      countryId\n      createdAt\n      dialCode\n      email\n      emailVerified\n      ibanNumber\n      id\n      isActive\n      languageCode\n      latitude\n      longitude\n      name\n      phone\n      phoneVerified\n      role\n      updatedAt\n      withAbsher\n      status\n    }\n  }\n": typeof types.ActivateUserDocument,
    "\n  mutation deactivateUser(\n    $deactivateUserId: ID!\n    $input: DeactivateUserInput!\n  ) {\n    deactivateUser(id: $deactivateUserId, input: $input) {\n      address\n      avatarFilename\n      bankName\n      categories {\n        createdAt\n        descriptionAr\n        descriptionEn\n        id\n        nameAr\n        nameEn\n        parentId\n        updatedAt\n      }\n      cityId\n      commercialRegistrationNumber\n      countryId\n      createdAt\n      dialCode\n      email\n      emailVerified\n      ibanNumber\n      id\n      isActive\n      languageCode\n      latitude\n      longitude\n      name\n      phone\n      phoneVerified\n      role\n      updatedAt\n      withAbsher\n      status\n      deactivationReason\n    }\n  }\n": typeof types.DeactivateUserDocument,
    "\n  mutation removeUser($removeUserId: ID!, $input: DeleteUserInput!) {\n    removeUser(id: $removeUserId, input: $input) {\n      address\n      avatarFilename\n      bankName\n      categories {\n        createdAt\n        descriptionAr\n        descriptionEn\n        id\n        nameAr\n        nameEn\n        parentId\n        updatedAt\n      }\n      cityId\n      commercialRegistrationNumber\n      countryId\n      createdAt\n      dialCode\n      email\n      emailVerified\n      ibanNumber\n      id\n      isActive\n      languageCode\n      latitude\n      longitude\n      name\n      phone\n      phoneVerified\n      role\n      updatedAt\n      withAbsher\n      status\n      deactivationReason\n      deleteReason\n      deletedAt\n    }\n  }\n": typeof types.RemoveUserDocument,
    "\n  query user($userId: ID!) {\n    user(id: $userId) {\n      address\n      avatarFilename\n      bankName\n      categories {\n        createdAt\n        descriptionAr\n        descriptionEn\n        id\n        nameAr\n        nameEn\n        parentId\n        updatedAt\n      }\n      cityId\n      commercialRegistrationNumber\n      countryId\n      createdAt\n      dialCode\n      email\n      emailVerified\n      ibanNumber\n      id\n      isActive\n      languageCode\n      latitude\n      longitude\n      name\n      phone\n      phoneVerified\n      role\n      updatedAt\n      withAbsher\n      status\n      city {\n        countryId\n        createdAt\n        id\n        nameAr\n        nameEn\n        updatedAt\n      }\n      deactivationReason\n      deleteReason\n      deletedAt\n    }\n  }\n": typeof types.UserDocument,
    "\n    query users($pagination: UserPaginationInput!) {\n      users(pagination: $pagination) {\n        meta {\n          hasNext\n          hasPrevious\n          limit\n          page\n          total\n          totalPages\n        }\n        items {\n          address\n          avatarFilename\n          bankName\n          categories {\n            createdAt\n            descriptionAr\n            descriptionEn\n            id\n            nameAr\n            nameEn\n            parentId\n            updatedAt\n          }\n          cityId\n          commercialRegistrationNumber\n          countryId\n          createdAt\n          dialCode\n          email\n          emailVerified\n          ibanNumber\n          id\n          isActive\n          languageCode\n          latitude\n          longitude\n          name\n          phone\n          phoneVerified\n          role\n          updatedAt\n          withAbsher\n          status\n        }\n      }\n    }\n  ": typeof types.UsersDocument,
};
const documents: Documents = {
    "\n  mutation activateAdmin($activateAdminId: ID!) {\n    activateAdmin(id: $activateAdminId) {\n      avatarFilename\n      createdAt\n      email\n      fullName\n      id\n      organizationName\n      permissionType\n      phoneNumber\n      roleName\n      status\n      updatedAt\n      userType\n    }\n  }\n": types.ActivateAdminDocument,
    "\n    query admin($adminId: ID!) {\n      admin(id: $adminId) {\n        createdAt\n        email\n        fullName\n        id\n        organizationName\n        permissionType\n        roleName\n        status\n        updatedAt\n        userType\n        phoneNumber\n      }\n    }\n  ": types.AdminDocument,
    "\n  query admins($paginationInput: AdminPaginationInput) {\n    admins(paginationInput: $paginationInput) {\n      meta {\n        hasNext\n        hasPrevious\n        limit\n        page\n        total\n        totalPages\n      }\n      items {\n        createdAt\n        email\n        fullName\n        id\n        organizationName\n        permissionType\n        roleName\n        status\n        updatedAt\n        userType\n        phoneNumber\n      }\n    }\n  }\n": types.AdminsDocument,
    "\n  mutation createAdmin($createAdminInput: CreateAdminInput!) {\n    createAdmin(createAdminInput: $createAdminInput) {\n      createdAt\n      email\n      fullName\n      id\n      organizationName\n      permissionType\n      roleName\n      status\n      updatedAt\n      userType\n      phoneNumber\n    }\n  }\n": types.CreateAdminDocument,
    "\n  mutation deactivateAdmin(\n    $deactivateAdminId: ID!\n    $input: DeactivateAdminInput!\n  ) {\n    deactivateAdmin(id: $deactivateAdminId, input: $input) {\n      avatarFilename\n      createdAt\n      email\n      fullName\n      id\n      organizationName\n      permissionType\n      phoneNumber\n      roleName\n      status\n      updatedAt\n      userType\n    }\n  }\n": types.DeactivateAdminDocument,
    "\n  query meAdmin {\n    meAdmin {\n      id\n      createdAt\n      email\n      fullName\n      organizationName\n      permissionType\n      roleName\n      status\n      updatedAt\n      userType\n      phoneNumber\n      avatarFilename\n    }\n  }\n": types.MeAdminDocument,
    "\n  mutation removeAdmin($removeAdminId: ID!) {\n    removeAdmin(id: $removeAdminId)\n  }\n": types.RemoveAdminDocument,
    "\n  mutation updateAdmin(\n    $updateAdminId: ID!\n    $updateAdminInput: UpdateAdminInput!\n  ) {\n    updateAdmin(id: $updateAdminId, updateAdminInput: $updateAdminInput) {\n      createdAt\n      email\n      fullName\n      id\n      organizationName\n      permissionType\n      roleName\n      status\n      updatedAt\n      userType\n      phoneNumber\n    }\n  }\n": types.UpdateAdminDocument,
    "\n  mutation adminChangePassword($input: AdminChangePasswordInput!) {\n    adminChangePassword(input: $input)\n  }\n": types.AdminChangePasswordDocument,
    "\n  mutation adminForgotPassword($input: AdminForgotPasswordInput!) {\n    adminForgotPassword(input: $input)\n  }\n": types.AdminForgotPasswordDocument,
    "\n  mutation adminLogin($input: AdminLoginInput!) {\n    adminLogin(input: $input) {\n      accessToken\n    }\n  }\n": types.AdminLoginDocument,
    "\n  mutation adminResetPassword($input: AdminResetPasswordInput!) {\n    adminResetPassword(input: $input)\n  }\n": types.AdminResetPasswordDocument,
    "\n  mutation adminVerifyPasswordResetOtp(\n    $input: VerifyAdminPasswordResetOtpInput!\n  ) {\n    adminVerifyPasswordResetOtp(input: $input) {\n      resetToken\n    }\n  }\n": types.AdminVerifyPasswordResetOtpDocument,
    "\n  query categories($input: CategoryPaginationInput) {\n    categories(input: $input) {\n      meta {\n        hasNext\n        hasPrevious\n        limit\n        page\n        total\n        totalPages\n      }\n      items {\n        createdAt\n        descriptionAr\n        descriptionEn\n        id\n        nameAr\n        nameEn\n        parentId\n        updatedAt\n        parent {\n          createdAt\n          descriptionAr\n          descriptionEn\n          id\n          nameAr\n          nameEn\n          parentId\n          updatedAt\n        }\n      }\n    }\n  }\n": types.CategoriesDocument,
    "\n  query category($categoryId: String!) {\n    category(id: $categoryId) {\n      createdAt\n      descriptionAr\n      descriptionEn\n      id\n      nameAr\n      nameEn\n      parent {\n        createdAt\n        descriptionAr\n        descriptionEn\n        id\n        nameAr\n        nameEn\n        parentId\n        updatedAt\n      }\n      parentId\n      updatedAt\n    }\n  }\n": types.CategoryDocument,
    "\n  mutation createCategory($input: CreateCategoryInput!) {\n    createCategory(input: $input) {\n      createdAt\n      descriptionAr\n      descriptionEn\n      id\n      nameAr\n      nameEn\n      parentId\n      updatedAt\n    }\n  }\n": types.CreateCategoryDocument,
    "\n  mutation removeCategory($removeCategoryId: String!) {\n    removeCategory(id: $removeCategoryId) {\n      id\n      createdAt\n      descriptionAr\n      descriptionEn\n      nameAr\n      nameEn\n      parentId\n      updatedAt\n    }\n  }\n": types.RemoveCategoryDocument,
    "\n  mutation updateCategory($input: UpdateCategoryInput!) {\n    updateCategory(input: $input) {\n      createdAt\n      descriptionAr\n      descriptionEn\n      id\n      nameAr\n      nameEn\n      parentId\n      updatedAt\n    }\n  }\n": types.UpdateCategoryDocument,
    "\n  query cities($pagination: CityPaginationInput) {\n    cities(pagination: $pagination) {\n      meta {\n        hasNext\n        hasPrevious\n        limit\n        page\n        total\n        totalPages\n      }\n      items {\n        countryId\n        createdAt\n        id\n        nameAr\n        nameEn\n        updatedAt\n        country {\n          code\n          createdAt\n          dialCode\n          id\n          nameAr\n          nameEn\n          updatedAt\n        }\n      }\n    }\n  }\n": types.CitiesDocument,
    "\n  query city($cityId: ID!) {\n    city(id: $cityId) {\n      id\n      nameAr\n      nameEn\n      updatedAt\n      createdAt\n      countryId\n      country {\n        code\n        createdAt\n        dialCode\n        id\n        nameAr\n        nameEn\n        updatedAt\n      }\n    }\n  }\n": types.CityDocument,
    "\n  query countries($pagination: CountryPaginationInput) {\n    countries(pagination: $pagination) {\n      meta {\n        hasNext\n        hasPrevious\n        limit\n        page\n        total\n        totalPages\n      }\n      items {\n        code\n        createdAt\n        dialCode\n        id\n        nameAr\n        nameEn\n        updatedAt\n      }\n    }\n  }\n": types.CountriesDocument,
    "\n  mutation createCity($input: CreateCityInput!) {\n    createCity(input: $input) {\n      id\n      countryId\n      createdAt\n      nameAr\n      nameEn\n      updatedAt\n      country {\n        code\n        createdAt\n        dialCode\n        id\n        nameAr\n        nameEn\n        updatedAt\n      }\n    }\n  }\n": types.CreateCityDocument,
    "\n  mutation removeCity($removeCityId: ID!) {\n    removeCity(id: $removeCityId) {\n      countryId\n      createdAt\n      id\n      nameAr\n      nameEn\n      updatedAt\n      country {\n        code\n        createdAt\n        dialCode\n        id\n        nameAr\n        nameEn\n        updatedAt\n      }\n    }\n  }\n": types.RemoveCityDocument,
    "\n  mutation updateCity($input: UpdateCityInput!) {\n    updateCity(input: $input) {\n      countryId\n      createdAt\n      id\n      nameAr\n      nameEn\n      updatedAt\n      country {\n        code\n        createdAt\n        dialCode\n        id\n        nameAr\n        nameEn\n        updatedAt\n      }\n    }\n  }\n": types.UpdateCityDocument,
    "\n  query adminPermissions($adminId: ID!) {\n    adminPermissions(adminId: $adminId) {\n      adminId\n      createdAt\n      id\n      permission {\n        action\n        createdAt\n        description\n        id\n        module\n        name\n        nameAr\n        permissionPlatform\n        resource\n        updatedAt\n      }\n      permissionId\n      updatedAt\n      admin {\n        createdAt\n        email\n        fullName\n        id\n        organizationName\n        permissionType\n        phoneNumber\n        roleName\n        status\n        updatedAt\n        userType\n      }\n    }\n  }\n": types.AdminPermissionsDocument,
    "\n  mutation bulkAssignPermissionsToAdmin($input: BulkAssignPermissionsInput!) {\n    bulkAssignPermissionsToAdmin(input: $input) {\n      adminId\n      createdAt\n      id\n      permission {\n        resource\n        action\n        createdAt\n        description\n        id\n        module\n        name\n        nameAr\n        permissionPlatform\n        updatedAt\n      }\n      admin {\n        createdAt\n        email\n        fullName\n        id\n        organizationName\n        permissionType\n        phoneNumber\n        roleName\n        status\n        updatedAt\n        userType\n      }\n      permissionId\n      updatedAt\n    }\n  }\n": types.BulkAssignPermissionsToAdminDocument,
    "\n  query permissions {\n    permissions {\n      action\n      createdAt\n      description\n      id\n      module\n      name\n      nameAr\n      permissionPlatform\n      resource\n      updatedAt\n    }\n  }\n": types.PermissionsDocument,
    "\n  query getSetting {\n    getSetting {\n      aboutAr\n      aboutEn\n      email\n      phones\n      privacyPolicyAr\n      privacyPolicyEn\n      socialMediaLinks {\n        link\n        name\n      }\n      termsAr\n      termsEn\n      whatsappNumber\n    }\n  }\n": types.GetSettingDocument,
    "\n  mutation setSetting($input: SettingInput!) {\n    setSetting(input: $input) {\n      aboutAr\n      aboutEn\n      email\n      phones\n      privacyPolicyAr\n      privacyPolicyEn\n      socialMediaLinks {\n        link\n        name\n      }\n      termsAr\n      termsEn\n      whatsappNumber\n    }\n  }\n": types.SetSettingDocument,
    "\n  mutation activateUser($activateUserId: ID!) {\n    activateUser(id: $activateUserId) {\n      address\n      avatarFilename\n      bankName\n      categories {\n        createdAt\n        descriptionAr\n        descriptionEn\n        id\n        nameAr\n        nameEn\n        parentId\n        updatedAt\n      }\n      cityId\n      commercialRegistrationNumber\n      countryId\n      createdAt\n      dialCode\n      email\n      emailVerified\n      ibanNumber\n      id\n      isActive\n      languageCode\n      latitude\n      longitude\n      name\n      phone\n      phoneVerified\n      role\n      updatedAt\n      withAbsher\n      status\n    }\n  }\n": types.ActivateUserDocument,
    "\n  mutation deactivateUser(\n    $deactivateUserId: ID!\n    $input: DeactivateUserInput!\n  ) {\n    deactivateUser(id: $deactivateUserId, input: $input) {\n      address\n      avatarFilename\n      bankName\n      categories {\n        createdAt\n        descriptionAr\n        descriptionEn\n        id\n        nameAr\n        nameEn\n        parentId\n        updatedAt\n      }\n      cityId\n      commercialRegistrationNumber\n      countryId\n      createdAt\n      dialCode\n      email\n      emailVerified\n      ibanNumber\n      id\n      isActive\n      languageCode\n      latitude\n      longitude\n      name\n      phone\n      phoneVerified\n      role\n      updatedAt\n      withAbsher\n      status\n      deactivationReason\n    }\n  }\n": types.DeactivateUserDocument,
    "\n  mutation removeUser($removeUserId: ID!, $input: DeleteUserInput!) {\n    removeUser(id: $removeUserId, input: $input) {\n      address\n      avatarFilename\n      bankName\n      categories {\n        createdAt\n        descriptionAr\n        descriptionEn\n        id\n        nameAr\n        nameEn\n        parentId\n        updatedAt\n      }\n      cityId\n      commercialRegistrationNumber\n      countryId\n      createdAt\n      dialCode\n      email\n      emailVerified\n      ibanNumber\n      id\n      isActive\n      languageCode\n      latitude\n      longitude\n      name\n      phone\n      phoneVerified\n      role\n      updatedAt\n      withAbsher\n      status\n      deactivationReason\n      deleteReason\n      deletedAt\n    }\n  }\n": types.RemoveUserDocument,
    "\n  query user($userId: ID!) {\n    user(id: $userId) {\n      address\n      avatarFilename\n      bankName\n      categories {\n        createdAt\n        descriptionAr\n        descriptionEn\n        id\n        nameAr\n        nameEn\n        parentId\n        updatedAt\n      }\n      cityId\n      commercialRegistrationNumber\n      countryId\n      createdAt\n      dialCode\n      email\n      emailVerified\n      ibanNumber\n      id\n      isActive\n      languageCode\n      latitude\n      longitude\n      name\n      phone\n      phoneVerified\n      role\n      updatedAt\n      withAbsher\n      status\n      city {\n        countryId\n        createdAt\n        id\n        nameAr\n        nameEn\n        updatedAt\n      }\n      deactivationReason\n      deleteReason\n      deletedAt\n    }\n  }\n": types.UserDocument,
    "\n    query users($pagination: UserPaginationInput!) {\n      users(pagination: $pagination) {\n        meta {\n          hasNext\n          hasPrevious\n          limit\n          page\n          total\n          totalPages\n        }\n        items {\n          address\n          avatarFilename\n          bankName\n          categories {\n            createdAt\n            descriptionAr\n            descriptionEn\n            id\n            nameAr\n            nameEn\n            parentId\n            updatedAt\n          }\n          cityId\n          commercialRegistrationNumber\n          countryId\n          createdAt\n          dialCode\n          email\n          emailVerified\n          ibanNumber\n          id\n          isActive\n          languageCode\n          latitude\n          longitude\n          name\n          phone\n          phoneVerified\n          role\n          updatedAt\n          withAbsher\n          status\n        }\n      }\n    }\n  ": types.UsersDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = graphql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function graphql(source: string): unknown;

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation activateAdmin($activateAdminId: ID!) {\n    activateAdmin(id: $activateAdminId) {\n      avatarFilename\n      createdAt\n      email\n      fullName\n      id\n      organizationName\n      permissionType\n      phoneNumber\n      roleName\n      status\n      updatedAt\n      userType\n    }\n  }\n"): (typeof documents)["\n  mutation activateAdmin($activateAdminId: ID!) {\n    activateAdmin(id: $activateAdminId) {\n      avatarFilename\n      createdAt\n      email\n      fullName\n      id\n      organizationName\n      permissionType\n      phoneNumber\n      roleName\n      status\n      updatedAt\n      userType\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query admin($adminId: ID!) {\n      admin(id: $adminId) {\n        createdAt\n        email\n        fullName\n        id\n        organizationName\n        permissionType\n        roleName\n        status\n        updatedAt\n        userType\n        phoneNumber\n      }\n    }\n  "): (typeof documents)["\n    query admin($adminId: ID!) {\n      admin(id: $adminId) {\n        createdAt\n        email\n        fullName\n        id\n        organizationName\n        permissionType\n        roleName\n        status\n        updatedAt\n        userType\n        phoneNumber\n      }\n    }\n  "];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query admins($paginationInput: AdminPaginationInput) {\n    admins(paginationInput: $paginationInput) {\n      meta {\n        hasNext\n        hasPrevious\n        limit\n        page\n        total\n        totalPages\n      }\n      items {\n        createdAt\n        email\n        fullName\n        id\n        organizationName\n        permissionType\n        roleName\n        status\n        updatedAt\n        userType\n        phoneNumber\n      }\n    }\n  }\n"): (typeof documents)["\n  query admins($paginationInput: AdminPaginationInput) {\n    admins(paginationInput: $paginationInput) {\n      meta {\n        hasNext\n        hasPrevious\n        limit\n        page\n        total\n        totalPages\n      }\n      items {\n        createdAt\n        email\n        fullName\n        id\n        organizationName\n        permissionType\n        roleName\n        status\n        updatedAt\n        userType\n        phoneNumber\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation createAdmin($createAdminInput: CreateAdminInput!) {\n    createAdmin(createAdminInput: $createAdminInput) {\n      createdAt\n      email\n      fullName\n      id\n      organizationName\n      permissionType\n      roleName\n      status\n      updatedAt\n      userType\n      phoneNumber\n    }\n  }\n"): (typeof documents)["\n  mutation createAdmin($createAdminInput: CreateAdminInput!) {\n    createAdmin(createAdminInput: $createAdminInput) {\n      createdAt\n      email\n      fullName\n      id\n      organizationName\n      permissionType\n      roleName\n      status\n      updatedAt\n      userType\n      phoneNumber\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation deactivateAdmin(\n    $deactivateAdminId: ID!\n    $input: DeactivateAdminInput!\n  ) {\n    deactivateAdmin(id: $deactivateAdminId, input: $input) {\n      avatarFilename\n      createdAt\n      email\n      fullName\n      id\n      organizationName\n      permissionType\n      phoneNumber\n      roleName\n      status\n      updatedAt\n      userType\n    }\n  }\n"): (typeof documents)["\n  mutation deactivateAdmin(\n    $deactivateAdminId: ID!\n    $input: DeactivateAdminInput!\n  ) {\n    deactivateAdmin(id: $deactivateAdminId, input: $input) {\n      avatarFilename\n      createdAt\n      email\n      fullName\n      id\n      organizationName\n      permissionType\n      phoneNumber\n      roleName\n      status\n      updatedAt\n      userType\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query meAdmin {\n    meAdmin {\n      id\n      createdAt\n      email\n      fullName\n      organizationName\n      permissionType\n      roleName\n      status\n      updatedAt\n      userType\n      phoneNumber\n      avatarFilename\n    }\n  }\n"): (typeof documents)["\n  query meAdmin {\n    meAdmin {\n      id\n      createdAt\n      email\n      fullName\n      organizationName\n      permissionType\n      roleName\n      status\n      updatedAt\n      userType\n      phoneNumber\n      avatarFilename\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation removeAdmin($removeAdminId: ID!) {\n    removeAdmin(id: $removeAdminId)\n  }\n"): (typeof documents)["\n  mutation removeAdmin($removeAdminId: ID!) {\n    removeAdmin(id: $removeAdminId)\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation updateAdmin(\n    $updateAdminId: ID!\n    $updateAdminInput: UpdateAdminInput!\n  ) {\n    updateAdmin(id: $updateAdminId, updateAdminInput: $updateAdminInput) {\n      createdAt\n      email\n      fullName\n      id\n      organizationName\n      permissionType\n      roleName\n      status\n      updatedAt\n      userType\n      phoneNumber\n    }\n  }\n"): (typeof documents)["\n  mutation updateAdmin(\n    $updateAdminId: ID!\n    $updateAdminInput: UpdateAdminInput!\n  ) {\n    updateAdmin(id: $updateAdminId, updateAdminInput: $updateAdminInput) {\n      createdAt\n      email\n      fullName\n      id\n      organizationName\n      permissionType\n      roleName\n      status\n      updatedAt\n      userType\n      phoneNumber\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation adminChangePassword($input: AdminChangePasswordInput!) {\n    adminChangePassword(input: $input)\n  }\n"): (typeof documents)["\n  mutation adminChangePassword($input: AdminChangePasswordInput!) {\n    adminChangePassword(input: $input)\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation adminForgotPassword($input: AdminForgotPasswordInput!) {\n    adminForgotPassword(input: $input)\n  }\n"): (typeof documents)["\n  mutation adminForgotPassword($input: AdminForgotPasswordInput!) {\n    adminForgotPassword(input: $input)\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation adminLogin($input: AdminLoginInput!) {\n    adminLogin(input: $input) {\n      accessToken\n    }\n  }\n"): (typeof documents)["\n  mutation adminLogin($input: AdminLoginInput!) {\n    adminLogin(input: $input) {\n      accessToken\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation adminResetPassword($input: AdminResetPasswordInput!) {\n    adminResetPassword(input: $input)\n  }\n"): (typeof documents)["\n  mutation adminResetPassword($input: AdminResetPasswordInput!) {\n    adminResetPassword(input: $input)\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation adminVerifyPasswordResetOtp(\n    $input: VerifyAdminPasswordResetOtpInput!\n  ) {\n    adminVerifyPasswordResetOtp(input: $input) {\n      resetToken\n    }\n  }\n"): (typeof documents)["\n  mutation adminVerifyPasswordResetOtp(\n    $input: VerifyAdminPasswordResetOtpInput!\n  ) {\n    adminVerifyPasswordResetOtp(input: $input) {\n      resetToken\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query categories($input: CategoryPaginationInput) {\n    categories(input: $input) {\n      meta {\n        hasNext\n        hasPrevious\n        limit\n        page\n        total\n        totalPages\n      }\n      items {\n        createdAt\n        descriptionAr\n        descriptionEn\n        id\n        nameAr\n        nameEn\n        parentId\n        updatedAt\n        parent {\n          createdAt\n          descriptionAr\n          descriptionEn\n          id\n          nameAr\n          nameEn\n          parentId\n          updatedAt\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query categories($input: CategoryPaginationInput) {\n    categories(input: $input) {\n      meta {\n        hasNext\n        hasPrevious\n        limit\n        page\n        total\n        totalPages\n      }\n      items {\n        createdAt\n        descriptionAr\n        descriptionEn\n        id\n        nameAr\n        nameEn\n        parentId\n        updatedAt\n        parent {\n          createdAt\n          descriptionAr\n          descriptionEn\n          id\n          nameAr\n          nameEn\n          parentId\n          updatedAt\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query category($categoryId: String!) {\n    category(id: $categoryId) {\n      createdAt\n      descriptionAr\n      descriptionEn\n      id\n      nameAr\n      nameEn\n      parent {\n        createdAt\n        descriptionAr\n        descriptionEn\n        id\n        nameAr\n        nameEn\n        parentId\n        updatedAt\n      }\n      parentId\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  query category($categoryId: String!) {\n    category(id: $categoryId) {\n      createdAt\n      descriptionAr\n      descriptionEn\n      id\n      nameAr\n      nameEn\n      parent {\n        createdAt\n        descriptionAr\n        descriptionEn\n        id\n        nameAr\n        nameEn\n        parentId\n        updatedAt\n      }\n      parentId\n      updatedAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation createCategory($input: CreateCategoryInput!) {\n    createCategory(input: $input) {\n      createdAt\n      descriptionAr\n      descriptionEn\n      id\n      nameAr\n      nameEn\n      parentId\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  mutation createCategory($input: CreateCategoryInput!) {\n    createCategory(input: $input) {\n      createdAt\n      descriptionAr\n      descriptionEn\n      id\n      nameAr\n      nameEn\n      parentId\n      updatedAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation removeCategory($removeCategoryId: String!) {\n    removeCategory(id: $removeCategoryId) {\n      id\n      createdAt\n      descriptionAr\n      descriptionEn\n      nameAr\n      nameEn\n      parentId\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  mutation removeCategory($removeCategoryId: String!) {\n    removeCategory(id: $removeCategoryId) {\n      id\n      createdAt\n      descriptionAr\n      descriptionEn\n      nameAr\n      nameEn\n      parentId\n      updatedAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation updateCategory($input: UpdateCategoryInput!) {\n    updateCategory(input: $input) {\n      createdAt\n      descriptionAr\n      descriptionEn\n      id\n      nameAr\n      nameEn\n      parentId\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  mutation updateCategory($input: UpdateCategoryInput!) {\n    updateCategory(input: $input) {\n      createdAt\n      descriptionAr\n      descriptionEn\n      id\n      nameAr\n      nameEn\n      parentId\n      updatedAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query cities($pagination: CityPaginationInput) {\n    cities(pagination: $pagination) {\n      meta {\n        hasNext\n        hasPrevious\n        limit\n        page\n        total\n        totalPages\n      }\n      items {\n        countryId\n        createdAt\n        id\n        nameAr\n        nameEn\n        updatedAt\n        country {\n          code\n          createdAt\n          dialCode\n          id\n          nameAr\n          nameEn\n          updatedAt\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query cities($pagination: CityPaginationInput) {\n    cities(pagination: $pagination) {\n      meta {\n        hasNext\n        hasPrevious\n        limit\n        page\n        total\n        totalPages\n      }\n      items {\n        countryId\n        createdAt\n        id\n        nameAr\n        nameEn\n        updatedAt\n        country {\n          code\n          createdAt\n          dialCode\n          id\n          nameAr\n          nameEn\n          updatedAt\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query city($cityId: ID!) {\n    city(id: $cityId) {\n      id\n      nameAr\n      nameEn\n      updatedAt\n      createdAt\n      countryId\n      country {\n        code\n        createdAt\n        dialCode\n        id\n        nameAr\n        nameEn\n        updatedAt\n      }\n    }\n  }\n"): (typeof documents)["\n  query city($cityId: ID!) {\n    city(id: $cityId) {\n      id\n      nameAr\n      nameEn\n      updatedAt\n      createdAt\n      countryId\n      country {\n        code\n        createdAt\n        dialCode\n        id\n        nameAr\n        nameEn\n        updatedAt\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query countries($pagination: CountryPaginationInput) {\n    countries(pagination: $pagination) {\n      meta {\n        hasNext\n        hasPrevious\n        limit\n        page\n        total\n        totalPages\n      }\n      items {\n        code\n        createdAt\n        dialCode\n        id\n        nameAr\n        nameEn\n        updatedAt\n      }\n    }\n  }\n"): (typeof documents)["\n  query countries($pagination: CountryPaginationInput) {\n    countries(pagination: $pagination) {\n      meta {\n        hasNext\n        hasPrevious\n        limit\n        page\n        total\n        totalPages\n      }\n      items {\n        code\n        createdAt\n        dialCode\n        id\n        nameAr\n        nameEn\n        updatedAt\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation createCity($input: CreateCityInput!) {\n    createCity(input: $input) {\n      id\n      countryId\n      createdAt\n      nameAr\n      nameEn\n      updatedAt\n      country {\n        code\n        createdAt\n        dialCode\n        id\n        nameAr\n        nameEn\n        updatedAt\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation createCity($input: CreateCityInput!) {\n    createCity(input: $input) {\n      id\n      countryId\n      createdAt\n      nameAr\n      nameEn\n      updatedAt\n      country {\n        code\n        createdAt\n        dialCode\n        id\n        nameAr\n        nameEn\n        updatedAt\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation removeCity($removeCityId: ID!) {\n    removeCity(id: $removeCityId) {\n      countryId\n      createdAt\n      id\n      nameAr\n      nameEn\n      updatedAt\n      country {\n        code\n        createdAt\n        dialCode\n        id\n        nameAr\n        nameEn\n        updatedAt\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation removeCity($removeCityId: ID!) {\n    removeCity(id: $removeCityId) {\n      countryId\n      createdAt\n      id\n      nameAr\n      nameEn\n      updatedAt\n      country {\n        code\n        createdAt\n        dialCode\n        id\n        nameAr\n        nameEn\n        updatedAt\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation updateCity($input: UpdateCityInput!) {\n    updateCity(input: $input) {\n      countryId\n      createdAt\n      id\n      nameAr\n      nameEn\n      updatedAt\n      country {\n        code\n        createdAt\n        dialCode\n        id\n        nameAr\n        nameEn\n        updatedAt\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation updateCity($input: UpdateCityInput!) {\n    updateCity(input: $input) {\n      countryId\n      createdAt\n      id\n      nameAr\n      nameEn\n      updatedAt\n      country {\n        code\n        createdAt\n        dialCode\n        id\n        nameAr\n        nameEn\n        updatedAt\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query adminPermissions($adminId: ID!) {\n    adminPermissions(adminId: $adminId) {\n      adminId\n      createdAt\n      id\n      permission {\n        action\n        createdAt\n        description\n        id\n        module\n        name\n        nameAr\n        permissionPlatform\n        resource\n        updatedAt\n      }\n      permissionId\n      updatedAt\n      admin {\n        createdAt\n        email\n        fullName\n        id\n        organizationName\n        permissionType\n        phoneNumber\n        roleName\n        status\n        updatedAt\n        userType\n      }\n    }\n  }\n"): (typeof documents)["\n  query adminPermissions($adminId: ID!) {\n    adminPermissions(adminId: $adminId) {\n      adminId\n      createdAt\n      id\n      permission {\n        action\n        createdAt\n        description\n        id\n        module\n        name\n        nameAr\n        permissionPlatform\n        resource\n        updatedAt\n      }\n      permissionId\n      updatedAt\n      admin {\n        createdAt\n        email\n        fullName\n        id\n        organizationName\n        permissionType\n        phoneNumber\n        roleName\n        status\n        updatedAt\n        userType\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation bulkAssignPermissionsToAdmin($input: BulkAssignPermissionsInput!) {\n    bulkAssignPermissionsToAdmin(input: $input) {\n      adminId\n      createdAt\n      id\n      permission {\n        resource\n        action\n        createdAt\n        description\n        id\n        module\n        name\n        nameAr\n        permissionPlatform\n        updatedAt\n      }\n      admin {\n        createdAt\n        email\n        fullName\n        id\n        organizationName\n        permissionType\n        phoneNumber\n        roleName\n        status\n        updatedAt\n        userType\n      }\n      permissionId\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  mutation bulkAssignPermissionsToAdmin($input: BulkAssignPermissionsInput!) {\n    bulkAssignPermissionsToAdmin(input: $input) {\n      adminId\n      createdAt\n      id\n      permission {\n        resource\n        action\n        createdAt\n        description\n        id\n        module\n        name\n        nameAr\n        permissionPlatform\n        updatedAt\n      }\n      admin {\n        createdAt\n        email\n        fullName\n        id\n        organizationName\n        permissionType\n        phoneNumber\n        roleName\n        status\n        updatedAt\n        userType\n      }\n      permissionId\n      updatedAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query permissions {\n    permissions {\n      action\n      createdAt\n      description\n      id\n      module\n      name\n      nameAr\n      permissionPlatform\n      resource\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  query permissions {\n    permissions {\n      action\n      createdAt\n      description\n      id\n      module\n      name\n      nameAr\n      permissionPlatform\n      resource\n      updatedAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query getSetting {\n    getSetting {\n      aboutAr\n      aboutEn\n      email\n      phones\n      privacyPolicyAr\n      privacyPolicyEn\n      socialMediaLinks {\n        link\n        name\n      }\n      termsAr\n      termsEn\n      whatsappNumber\n    }\n  }\n"): (typeof documents)["\n  query getSetting {\n    getSetting {\n      aboutAr\n      aboutEn\n      email\n      phones\n      privacyPolicyAr\n      privacyPolicyEn\n      socialMediaLinks {\n        link\n        name\n      }\n      termsAr\n      termsEn\n      whatsappNumber\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation setSetting($input: SettingInput!) {\n    setSetting(input: $input) {\n      aboutAr\n      aboutEn\n      email\n      phones\n      privacyPolicyAr\n      privacyPolicyEn\n      socialMediaLinks {\n        link\n        name\n      }\n      termsAr\n      termsEn\n      whatsappNumber\n    }\n  }\n"): (typeof documents)["\n  mutation setSetting($input: SettingInput!) {\n    setSetting(input: $input) {\n      aboutAr\n      aboutEn\n      email\n      phones\n      privacyPolicyAr\n      privacyPolicyEn\n      socialMediaLinks {\n        link\n        name\n      }\n      termsAr\n      termsEn\n      whatsappNumber\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation activateUser($activateUserId: ID!) {\n    activateUser(id: $activateUserId) {\n      address\n      avatarFilename\n      bankName\n      categories {\n        createdAt\n        descriptionAr\n        descriptionEn\n        id\n        nameAr\n        nameEn\n        parentId\n        updatedAt\n      }\n      cityId\n      commercialRegistrationNumber\n      countryId\n      createdAt\n      dialCode\n      email\n      emailVerified\n      ibanNumber\n      id\n      isActive\n      languageCode\n      latitude\n      longitude\n      name\n      phone\n      phoneVerified\n      role\n      updatedAt\n      withAbsher\n      status\n    }\n  }\n"): (typeof documents)["\n  mutation activateUser($activateUserId: ID!) {\n    activateUser(id: $activateUserId) {\n      address\n      avatarFilename\n      bankName\n      categories {\n        createdAt\n        descriptionAr\n        descriptionEn\n        id\n        nameAr\n        nameEn\n        parentId\n        updatedAt\n      }\n      cityId\n      commercialRegistrationNumber\n      countryId\n      createdAt\n      dialCode\n      email\n      emailVerified\n      ibanNumber\n      id\n      isActive\n      languageCode\n      latitude\n      longitude\n      name\n      phone\n      phoneVerified\n      role\n      updatedAt\n      withAbsher\n      status\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation deactivateUser(\n    $deactivateUserId: ID!\n    $input: DeactivateUserInput!\n  ) {\n    deactivateUser(id: $deactivateUserId, input: $input) {\n      address\n      avatarFilename\n      bankName\n      categories {\n        createdAt\n        descriptionAr\n        descriptionEn\n        id\n        nameAr\n        nameEn\n        parentId\n        updatedAt\n      }\n      cityId\n      commercialRegistrationNumber\n      countryId\n      createdAt\n      dialCode\n      email\n      emailVerified\n      ibanNumber\n      id\n      isActive\n      languageCode\n      latitude\n      longitude\n      name\n      phone\n      phoneVerified\n      role\n      updatedAt\n      withAbsher\n      status\n      deactivationReason\n    }\n  }\n"): (typeof documents)["\n  mutation deactivateUser(\n    $deactivateUserId: ID!\n    $input: DeactivateUserInput!\n  ) {\n    deactivateUser(id: $deactivateUserId, input: $input) {\n      address\n      avatarFilename\n      bankName\n      categories {\n        createdAt\n        descriptionAr\n        descriptionEn\n        id\n        nameAr\n        nameEn\n        parentId\n        updatedAt\n      }\n      cityId\n      commercialRegistrationNumber\n      countryId\n      createdAt\n      dialCode\n      email\n      emailVerified\n      ibanNumber\n      id\n      isActive\n      languageCode\n      latitude\n      longitude\n      name\n      phone\n      phoneVerified\n      role\n      updatedAt\n      withAbsher\n      status\n      deactivationReason\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation removeUser($removeUserId: ID!, $input: DeleteUserInput!) {\n    removeUser(id: $removeUserId, input: $input) {\n      address\n      avatarFilename\n      bankName\n      categories {\n        createdAt\n        descriptionAr\n        descriptionEn\n        id\n        nameAr\n        nameEn\n        parentId\n        updatedAt\n      }\n      cityId\n      commercialRegistrationNumber\n      countryId\n      createdAt\n      dialCode\n      email\n      emailVerified\n      ibanNumber\n      id\n      isActive\n      languageCode\n      latitude\n      longitude\n      name\n      phone\n      phoneVerified\n      role\n      updatedAt\n      withAbsher\n      status\n      deactivationReason\n      deleteReason\n      deletedAt\n    }\n  }\n"): (typeof documents)["\n  mutation removeUser($removeUserId: ID!, $input: DeleteUserInput!) {\n    removeUser(id: $removeUserId, input: $input) {\n      address\n      avatarFilename\n      bankName\n      categories {\n        createdAt\n        descriptionAr\n        descriptionEn\n        id\n        nameAr\n        nameEn\n        parentId\n        updatedAt\n      }\n      cityId\n      commercialRegistrationNumber\n      countryId\n      createdAt\n      dialCode\n      email\n      emailVerified\n      ibanNumber\n      id\n      isActive\n      languageCode\n      latitude\n      longitude\n      name\n      phone\n      phoneVerified\n      role\n      updatedAt\n      withAbsher\n      status\n      deactivationReason\n      deleteReason\n      deletedAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query user($userId: ID!) {\n    user(id: $userId) {\n      address\n      avatarFilename\n      bankName\n      categories {\n        createdAt\n        descriptionAr\n        descriptionEn\n        id\n        nameAr\n        nameEn\n        parentId\n        updatedAt\n      }\n      cityId\n      commercialRegistrationNumber\n      countryId\n      createdAt\n      dialCode\n      email\n      emailVerified\n      ibanNumber\n      id\n      isActive\n      languageCode\n      latitude\n      longitude\n      name\n      phone\n      phoneVerified\n      role\n      updatedAt\n      withAbsher\n      status\n      city {\n        countryId\n        createdAt\n        id\n        nameAr\n        nameEn\n        updatedAt\n      }\n      deactivationReason\n      deleteReason\n      deletedAt\n    }\n  }\n"): (typeof documents)["\n  query user($userId: ID!) {\n    user(id: $userId) {\n      address\n      avatarFilename\n      bankName\n      categories {\n        createdAt\n        descriptionAr\n        descriptionEn\n        id\n        nameAr\n        nameEn\n        parentId\n        updatedAt\n      }\n      cityId\n      commercialRegistrationNumber\n      countryId\n      createdAt\n      dialCode\n      email\n      emailVerified\n      ibanNumber\n      id\n      isActive\n      languageCode\n      latitude\n      longitude\n      name\n      phone\n      phoneVerified\n      role\n      updatedAt\n      withAbsher\n      status\n      city {\n        countryId\n        createdAt\n        id\n        nameAr\n        nameEn\n        updatedAt\n      }\n      deactivationReason\n      deleteReason\n      deletedAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query users($pagination: UserPaginationInput!) {\n      users(pagination: $pagination) {\n        meta {\n          hasNext\n          hasPrevious\n          limit\n          page\n          total\n          totalPages\n        }\n        items {\n          address\n          avatarFilename\n          bankName\n          categories {\n            createdAt\n            descriptionAr\n            descriptionEn\n            id\n            nameAr\n            nameEn\n            parentId\n            updatedAt\n          }\n          cityId\n          commercialRegistrationNumber\n          countryId\n          createdAt\n          dialCode\n          email\n          emailVerified\n          ibanNumber\n          id\n          isActive\n          languageCode\n          latitude\n          longitude\n          name\n          phone\n          phoneVerified\n          role\n          updatedAt\n          withAbsher\n          status\n        }\n      }\n    }\n  "): (typeof documents)["\n    query users($pagination: UserPaginationInput!) {\n      users(pagination: $pagination) {\n        meta {\n          hasNext\n          hasPrevious\n          limit\n          page\n          total\n          totalPages\n        }\n        items {\n          address\n          avatarFilename\n          bankName\n          categories {\n            createdAt\n            descriptionAr\n            descriptionEn\n            id\n            nameAr\n            nameEn\n            parentId\n            updatedAt\n          }\n          cityId\n          commercialRegistrationNumber\n          countryId\n          createdAt\n          dialCode\n          email\n          emailVerified\n          ibanNumber\n          id\n          isActive\n          languageCode\n          latitude\n          longitude\n          name\n          phone\n          phoneVerified\n          role\n          updatedAt\n          withAbsher\n          status\n        }\n      }\n    }\n  "];

export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;