import * as Flags from "country-flag-icons/react/3x2";

export const COUNTRY_CODE_LIST = [
  {
    value: "+966",
    labelAr: "السعودية",
    labelEn: "Saudi Arabia",
    Flag: Flags.SA,
  },
  {
    value: "+971",
    labelAr: "الإمارات العربية المتحدة",
    labelEn: "United Arab Emirates",
    Flag: Flags.AE,
  },
  { value: "+965", labelAr: "الكويت", labelEn: "Kuwait", Flag: Flags.KW },
  { value: "+974", labelAr: "قطر", labelEn: "Qatar", Flag: Flags.QA },
  { value: "+973", labelAr: "البحرين", labelEn: "Bahrain", Flag: Flags.BH },
  { value: "+968", labelAr: "عُمان", labelEn: "Oman", Flag: Flags.OM },
  { value: "+20", labelAr: "مصر", labelEn: "Egypt", Flag: Flags.EG },
  { value: "+962", labelAr: "الأردن", labelEn: "Jordan", Flag: Flags.JO },
  { value: "+961", labelAr: "لبنان", labelEn: "Lebanon", Flag: Flags.LB },
  { value: "+963", labelAr: "سوريا", labelEn: "Syria", Flag: Flags.SY },
  { value: "+964", labelAr: "العراق", labelEn: "Iraq", Flag: Flags.IQ },
  { value: "+212", labelAr: "المغرب", labelEn: "Morocco", Flag: Flags.MA },
  { value: "+213", labelAr: "الجزائر", labelEn: "Algeria", Flag: Flags.DZ },
  { value: "+216", labelAr: "تونس", labelEn: "Tunisia", Flag: Flags.TN },
  { value: "+218", labelAr: "ليبيا", labelEn: "Libya", Flag: Flags.LY },
  { value: "+249", labelAr: "السودان", labelEn: "Sudan", Flag: Flags.SD },
  { value: "+967", labelAr: "اليمن", labelEn: "Yemen", Flag: Flags.YE },
  {
    value: "+1",
    labelAr: "الولايات المتحدة",
    labelEn: "United States",
    Flag: Flags.US,
  },
  { value: "+1", labelAr: "كندا", labelEn: "Canada", Flag: Flags.CA },
  {
    value: "+44",
    labelAr: "المملكة المتحدة",
    labelEn: "United Kingdom",
    Flag: Flags.GB,
  },
  { value: "+33", labelAr: "فرنسا", labelEn: "France", Flag: Flags.FR },
  { value: "+49", labelAr: "ألمانيا", labelEn: "Germany", Flag: Flags.DE },
  { value: "+39", labelAr: "إيطاليا", labelEn: "Italy", Flag: Flags.IT },
  { value: "+34", labelAr: "إسبانيا", labelEn: "Spain", Flag: Flags.ES },
  { value: "+90", labelAr: "تركيا", labelEn: "Turkey", Flag: Flags.TR },
  { value: "+91", labelAr: "الهند", labelEn: "India", Flag: Flags.IN },
  { value: "+92", labelAr: "باكستان", labelEn: "Pakistan", Flag: Flags.PK },
  { value: "+880", labelAr: "بنغلاديش", labelEn: "Bangladesh", Flag: Flags.BD },
  { value: "+86", labelAr: "الصين", labelEn: "China", Flag: Flags.CN },
  { value: "+81", labelAr: "اليابان", labelEn: "Japan", Flag: Flags.JP },
  {
    value: "+82",
    labelAr: "كوريا الجنوبية",
    labelEn: "South Korea",
    Flag: Flags.KR,
  },
  { value: "+61", labelAr: "أستراليا", labelEn: "Australia", Flag: Flags.AU },
  { value: "+55", labelAr: "البرازيل", labelEn: "Brazil", Flag: Flags.BR },
  { value: "+52", labelAr: "المكسيك", labelEn: "Mexico", Flag: Flags.MX },
  { value: "+7", labelAr: "روسيا", labelEn: "Russia", Flag: Flags.RU },
  {
    value: "+27",
    labelAr: "جنوب أفريقيا",
    labelEn: "South Africa",
    Flag: Flags.ZA,
  },
  { value: "+234", labelAr: "نيجيريا", labelEn: "Nigeria", Flag: Flags.NG },
  { value: "+254", labelAr: "كينيا", labelEn: "Kenya", Flag: Flags.KE },
  { value: "+251", labelAr: "إثيوبيا", labelEn: "Ethiopia", Flag: Flags.ET },
  { value: "+233", labelAr: "غانا", labelEn: "Ghana", Flag: Flags.GH },
];
