export enum ExportModel {
  MAIN_CATEGORY = "mainCategory",
  SUBCATEGORY = "subcategory",
  PRODUCT = "product",
  USER = "user",
  WAREHOUSE = "warehouse",
  SUPPLIER = "supplier",
  CUSTOMER = "customer",
  DRIVER = "driver",
  SHIPMENT = "shipment",
  INVENTORY = "inventory",
  WITHDRAWAL_ORDER = "withdrawalOrder",
  RECEIPT_ORDER = "receiptOrder",
  INVOICE = "invoice",
  CONTRACT = "contract",
  STORAGE_SPACE = "storageSpace",
  RETURN_REQUEST = "returnRequest",
  PURCHASE_ORDER = "purchaseOrder",
  LEASE = "lease",
}
